name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  dockerbuild:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Build and Run Docker Image
      run: |
        IMAGE_TAG=workflow-test:$(date +%s)
        docker build . --tag $IMAGE_TAG
        docker run --rm $IMAGE_TAG

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Uncomment if tests are added
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flask pytest

    # - name: Run tests
    #   run: pytest

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub