name: CI/CD for Dockerized Flask App with Minikube

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

     # - name: Run tests
     #   run: pytest

  deploy-to-minikube:
    needs: build-and-test
    runs-on: [self-hosted, minikube-runner]  # Your Minikube is running here
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Use Minikube Docker daemon
        run: |
          eval $(minikube docker-env)
          docker build -t flasktest-app:latest .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/Deployment.yaml
          kubectl apply -f k8s/Service.yaml

      - name: Continuous Monitoring - Verify Deployment Rollout
        run: |
          kubectl rollout status deployment flask-app