name: CI/CD with Minikube Deployment

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  dockerbuild:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set Docker env to Minikube
        run: eval $(minikube docker-env)

      - name: Build Docker image for Minikube
        run: |
          docker build . -t flask-dev-image:latest

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy-to-minikube:
    needs: [dockerbuild, build-and-test]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set kubectl context to Minikube
        run: |
          kubectl config use-context minikube

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml

      - name: Wait for Deployment to become ready
        run: |
          kubectl rollout status deployment/flask-app